=== DnyKristof/GQOKMW_XMLgyak/XMLTaskGQOKMW/src/XMLSchemaGQOKMW.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Nev" type="xs:string"/>
    <xs:element name="Hatarido" type="xs:date"/>
    <xs:element name="Utca" type="xs:string"/>
    <xs:element name="Varos" type="xs:string"/>
    <xs:element name="Hazszam" type="xs:string"/>
    <xs:element name="Megrendelesideje" type="xs:date"/>
    <xs:element name="Statusz" type="xs:string"/>
    <xs:element name="Learazas" type="xs:float"/>
    <xs:element name="Mennyiseg" type="xs:positiveInteger"/>
    <xs:element name="Listaar" type="xs:int"/>
    <xs:element name="Fizetes" type="xs:positiveInteger"/>

    <xs:complexType name="cimType">
        <xs:sequence>
            <xs:element ref="Utca"/>
            <xs:element ref="Varos"/>
            <xs:element ref="Hazszam"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="telefonszamType">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{4}-\d{7}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="Vasarlo">
        <xs:sequence>
            <xs:element ref="Nev"/>
            <xs:element type="cimType" name="Cim"/>
            <xs:element type="telefonszamType" name="Telefonszam" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="V_id" type="xs:positiveInteger" use="required"/>
        <xs:attribute name="M_id" type="xs:positiveInteger" use="required"/>
    </xs:complexType>

    <xs:complexType name="Megrendeles">
        <xs:sequence>
            <xs:element ref="Hatarido"/>
            <xs:element ref="Megrendelesideje"/>
            <xs:element ref="Statusz"/>
        </xs:sequence>
        <xs:attribute name="M_id" type="xs:positiveInteger" use="required"/>
    </xs:complexType>

    <xs:complexType name="Megrendelttermek">
        <xs:sequence>
            <xs:element ref="Learazas"/>
            <xs:element ref="Mennyiseg"/>
            <xs:element ref="Listaar"/>
        </xs:sequence>
        <xs:attribute name="M_id" type="xs:positiveInteger" use="required"/>
        <xs:attribute name="MT_id" type="xs:positiveInteger" use="required"/>
    </xs:complexType>

    <xs:complexType name="Üzlet">
        <xs:sequence>
            <xs:element type="cimType" name="Cim"/>
            <xs:element ref="Nev"/>
            <xs:element type="telefonszamType" name="Telefonszam" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="Ü_id" type="xs:positiveInteger" use="required"/>
        <xs:attribute name="MT_id" type="xs:positiveInteger" use="required"/>
    </xs:complexType>

    <xs:complexType name="Ü_D">
        <xs:sequence>
            <xs:element ref="Fizetes"/>
        </xs:sequence>
        <xs:attribute name="Ü_id" type="xs:positiveInteger" use="required"/>
        <xs:attribute name="D_id" type="xs:positiveInteger" use="required"/>
    </xs:complexType>

    <xs:complexType name="Dolgozo">
        <xs:sequence>
            <xs:element type="cimType" name="Cim"/>
            <xs:element ref="Nev"/>
            <xs:element type="telefonszamType" name="Telefonszam" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="D_id" type="xs:positiveInteger" use="required"/>
    </xs:complexType>

    <xs:element name="GQOKMW_BEADANDO">
        <xs:complexType>
            <xs:sequence>
                <xs:element type="Vasarlo" name="Vasarlo" maxOccurs="unbounded"/>
                <xs:element type="Megrendeles" name="Megrendeles" maxOccurs="unbounded"/>
                <xs:element type="Megrendelttermek" name="Megrendelttermek" maxOccurs="unbounded"/>
                <xs:element type="Üzlet" name="Üzlet" maxOccurs="unbounded"/>
                <xs:element type="Ü_D" name="Ü_D" maxOccurs="unbounded"/>
                <xs:element type="Dolgozo" name="Dolgozo" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
        
        <!-- Egyedi kulcsok -->
        <xs:key name="Vasarlo_V_id">
            <xs:selector xpath="Vasarlo"/>
            <xs:field xpath="@V_id"/>
        </xs:key>
        <xs:key name="Megrendeles_M_id">
            <xs:selector xpath="Megrendeles"/>
            <xs:field xpath="@M_id"/>
        </xs:key>
        <xs:key name="Megrendelttermek_MT_id">
            <xs:selector xpath="Megrendelttermek"/>
            <xs:field xpath="@MT_id"/>
        </xs:key>
        <xs:key name="Üzlet_Ü_id">
            <xs:selector xpath="Üzlet"/>
            <xs:field xpath="@Ü_id"/>
        </xs:key>
        <xs:key name="Dolgozok_D_id">
            <xs:selector xpath="Dolgozo"/>
            <xs:field xpath="@D_id"/>
        </xs:key>

        <!-- Idegen kulcsok -->
        <xs:keyref name="Vasarlo_Megrendeles_id_ref" refer="Megrendeles_M_id">
            <xs:selector xpath="Vasarlo"/>
            <xs:field xpath="@M_id"/>
        </xs:keyref>
        <xs:keyref name="Megrendelttermek_Megrendeles_id_ref" refer="Megrendeles_M_id">
            <xs:selector xpath="Megrendelttermek"/>
            <xs:field xpath="@M_id"/>
        </xs:keyref>
        <xs:keyref name="Üzlet_Megrendelttermek_id_ref" refer="Megrendelttermek_MT_id">
            <xs:selector xpath="Üzlet"/>
            <xs:field xpath="@MT_id"/>
        </xs:keyref>
        <xs:keyref name="Ü_D_Üzlet_id_ref" refer="Üzlet_Ü_id">
            <xs:selector xpath="Ü_D"/>
            <xs:field xpath="@Ü_id"/>
        </xs:keyref>
        <xs:keyref name="Ü_D_Dolgozo_id_ref" refer="Dolgozok_D_id">
            <xs:selector xpath="Ü_D"/>
            <xs:field xpath="@D_id"/>
        </xs:keyref>

        <!-- Egy-egy kapcsolat -->
        <xs:unique name="Megrendeles_M_id_unique">
            <xs:selector xpath="Vasarlo"/>
            <xs:field xpath="@M_id"/>
        </xs:unique>


    </xs:element>


</xs:schema>

=== DnyKristof/GQOKMW_XMLgyak/XMLTaskGQOKMW/XMLGQOKMW.xml
<?xml version="1.0" encoding="UTF-8"?>
<GQOKMW_BEADANDO xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
    xs:noNamespaceSchemaLocation="XMLSchemaGQOKMW.xsd">

    <!-- Vásárlók -->
    <Vasarlo V_id="1" M_id="01">
        <Nev>Kiss Ádám</Nev>
        <Cim>
            <Utca>Kossuth Lajos utca</Utca>
            <Varos>Miskolc</Varos>
            <Hazszam>1</Hazszam>
        </Cim>
        <Telefonszam>0630-1234567</Telefonszam>
    </Vasarlo>

    <Vasarlo V_id="2" M_id="02">
        <Nev>Nagy Pista</Nev>
        <Cim>
            <Utca>Árpád utca</Utca>
            <Varos>Szekszárd</Varos>
            <Hazszam>5</Hazszam>
        </Cim>
        <Telefonszam>0630-3214569</Telefonszam>
    </Vasarlo>

    <Vasarlo V_id="3" M_id="03">
        <Nev>Nagy Máté</Nev>
        <Cim>
            <Utca>József Attila út</Utca>
            <Varos>Esztergom</Varos>
            <Hazszam>5</Hazszam>
        </Cim>
        <Telefonszam>0630-1234765</Telefonszam>
        <Telefonszam>0630-7654321</Telefonszam>
    </Vasarlo>

    <!-- Megrendelés -->

    <Megrendeles M_id="01">
        <Hatarido>2021-02-03</Hatarido>
        <Megrendelesideje>2021-02-01</Megrendelesideje>
        <Statusz>Teljesítve</Statusz>
    </Megrendeles>

    <Megrendeles M_id="02">
        <Hatarido>2021-02-07</Hatarido>
        <Megrendelesideje>2021-02-02</Megrendelesideje>
        <Statusz>Szállítás alatt</Statusz>
    </Megrendeles>

    <Megrendeles M_id="03">
        <Hatarido>2021-03-05</Hatarido>
        <Megrendelesideje>2021-03-01</Megrendelesideje>
        <Statusz>Teljesítve</Statusz>
    </Megrendeles>

    <!-- Megrendelt termék-->

    <Megrendelttermek M_id="01" MT_id="11">
        <Learazas>0.2</Learazas>
        <Mennyiseg>2</Mennyiseg>
        <Listaar>25000</Listaar>
    </Megrendelttermek>

    <Megrendelttermek M_id="02" MT_id="12">
        <Learazas>0.2</Learazas>
        <Mennyiseg>2</Mennyiseg>
        <Listaar>25000</Listaar>
    </Megrendelttermek>

    <Megrendelttermek M_id="03" MT_id="13">
        <Learazas>0.2</Learazas>
        <Mennyiseg>2</Mennyiseg>
        <Listaar>25000</Listaar>
    </Megrendelttermek>

    <!-- Üzlet -->

    <Üzlet Ü_id="21" MT_id="11">
        <Cim>
            <Utca>Lajos utca</Utca>
            <Varos>Miskolc</Varos>
            <Hazszam>6</Hazszam>
        </Cim>
        <Nev>Hervis</Nev>
        <Telefonszam>0670-5312490</Telefonszam>
        <Telefonszam>0630-6587421</Telefonszam>
    </Üzlet>

    <Üzlet Ü_id="22" MT_id="12">
        <Cim>
            <Utca>Lajos utca</Utca>
            <Varos>Miskolc</Varos>
            <Hazszam>6</Hazszam>
        </Cim>
        <Nev>Intersport</Nev>
        <Telefonszam>0670-5312490</Telefonszam>
        <Telefonszam>0630-6587421</Telefonszam>
    </Üzlet>

    <Üzlet Ü_id="23" MT_id="13">
        <Cim>
            <Utca>Lajos utca</Utca>
            <Varos>Miskolc</Varos>
            <Hazszam>6</Hazszam>
        </Cim>
        <Nev>Dechatlon</Nev>
        <Telefonszam>0670-5312490</Telefonszam>
        <Telefonszam>0630-6587421</Telefonszam>
    </Üzlet>

    <!-- Ü_D -->
    <Ü_D Ü_id="21" D_id="31">
        <Fizetes>420000</Fizetes>
    </Ü_D>
    <Ü_D Ü_id="22" D_id="32">
        <Fizetes>530000</Fizetes>
    </Ü_D>
    <Ü_D Ü_id="23" D_id="33">
        <Fizetes>370000</Fizetes>
    </Ü_D>

    <!-- Dolgozók -->

    <Dolgozo D_id="31">
        <Cim>
            <Utca>Oláh Lajos</Utca>
            <Varos>Miskolc</Varos>
            <Hazszam>6</Hazszam>
        </Cim>
        <Nev>Nagy Gergő</Nev>
        <Telefonszam>0670-5342490</Telefonszam>
        <Telefonszam>0630-6596521</Telefonszam>
    </Dolgozo>

    <Dolgozo D_id="32">
        <Cim>
            <Utca>Deaák ferenc</Utca>
            <Varos>Arnót</Varos>
            <Hazszam>8</Hazszam>
        </Cim>
        <Nev>Kiss Árpád</Nev>
        <Telefonszam>0670-5643905</Telefonszam>
        <Telefonszam>0630-6734524</Telefonszam>
    </Dolgozo>

    <Dolgozo D_id="33">
        <Cim>
            <Utca>Kossuth Lajos</Utca>
            <Varos>Miskolc</Varos>
            <Hazszam>56</Hazszam>
        </Cim>
        <Nev>Szabó Gergő</Nev>
        <Telefonszam>0670-5723490</Telefonszam>
        <Telefonszam>0630-9654321</Telefonszam>
    </Dolgozo>

</GQOKMW_BEADANDO>

=== DnyKristof/GQOKMW_XMLgyak/GQOKMW_BEADANDO/XMLGQOKMW.xml
<?xml version="1.0" encoding="UTF-8"?>
<GQOKMW_BEADANDO xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
    xs:noNamespaceSchemaLocation="XMLSchemaGQOKMW.xsd">

    <!-- Vásárlók -->
    <Vasarlo V_id="1" M_id="01">
        <Nev>Ádám</Nev>
        <Cim>
            <Utca>Árpád utca</Utca>
            <Varos>Budapest</Varos>
            <Hazszam>1</Hazszam>
        </Cim>
        <Telefonszam>0630-1234567</Telefonszam>
    </Vasarlo>

    <Vasarlo V_id="2" M_id="02">
        <Nev>Ádám</Nev>
        <Cim>
            <Utca>Árpád utca</Utca>
            <Varos>Budapest</Varos>
            <Hazszam>1</Hazszam>
        </Cim>
        <Telefonszam>0630-1234567</Telefonszam>
    </Vasarlo>

    <Vasarlo V_id="3" M_id="03">
        <Nev>Ádám</Nev>
        <Cim>
            <Utca>Árpád utca</Utca>
            <Varos>Budapest</Varos>
            <Hazszam>1</Hazszam>
        </Cim>
        <Telefonszam>0630-1234567</Telefonszam>
        <Telefonszam>0630-7654321</Telefonszam>
    </Vasarlo>

    <!-- Megrendelés -->

    <Megrendeles M_id="01">
        <Hatarido>2021-02-03</Hatarido>
        <Megrendelesideje>2021-02-01</Megrendelesideje>
        <Statusz>Teljesítve</Statusz>
    </Megrendeles>

    <Megrendeles M_id="02">
        <Hatarido>2021-02-07</Hatarido>
        <Megrendelesideje>2021-02-02</Megrendelesideje>
        <Statusz>Szállítás alatt</Statusz>
    </Megrendeles>

    <Megrendeles M_id="03">
        <Hatarido>2021-03-05</Hatarido>
        <Megrendelesideje>2021-03-01</Megrendelesideje>
        <Statusz>Teljesítve</Statusz>
    </Megrendeles>

    <!-- Megrendelt termék-->

    <Megrendelttermék M_id="01" MT_id="11">
        <Learazas>0.2</Learazas>
        <Mennyiség>2</Mennyiség>
        <Listaar>25000</Listaar>
    </Megrendelttermék>

    <Megrendelttermék M_id="02" MT_id="12">
        <Learazas>0.2</Learazas>
        <Mennyiség>2</Mennyiség>
        <Listaar>25000</Listaar>
    </Megrendelttermék>

    <Megrendelttermék M_id="03" MT_id="13">
        <Learazas>0.2</Learazas>
        <Mennyiség>2</Mennyiség>
        <Listaar>25000</Listaar>
    </Megrendelttermék>

    <!-- Üzlet -->

    <Üzlet Ü_id="21" MT_id="11">
        <Cim>
            <Utca>Lajos utca</Utca>
            <Varos>Miskolc</Varos>
            <Hazszam>6</Hazszam>
        </Cim>
        <Nev>Hervis</Nev>
        <Telefonszam>0670-5312490</Telefonszam>
        <Telefonszam>0630-6587421</Telefonszam>
    </Üzlet>

    <Üzlet Ü_id="22" MT_id="12">
        <Cim>
            <Utca>Lajos utca</Utca>
            <Varos>Miskolc</Varos>
            <Hazszam>6</Hazszam>
        </Cim>
        <Nev>Intersport</Nev>
        <Telefonszam>0670-5312490</Telefonszam>
        <Telefonszam>0630-6587421</Telefonszam>
    </Üzlet>

    <Üzlet Ü_id="23" MT_id="13">
        <Cim>
            <Utca>Lajos utca</Utca>
            <Varos>Miskolc</Varos>
            <Hazszam>6</Hazszam>
        </Cim>
        <Nev>Dechatlon</Nev>
        <Telefonszam>0670-5312490</Telefonszam>
        <Telefonszam>0630-6587421</Telefonszam>
    </Üzlet>

    <!-- Ü_D -->
    <Ü_D Ü_id="21" D_id="31">
        <Fizetes>420000</Fizetes>
    </Ü_D>
    <Ü_D Ü_id="22" D_id="32">
        <Fizetes>530000</Fizetes>
    </Ü_D>
    <Ü_D Ü_id="23" D_id="33">
        <Fizetes>370000</Fizetes>
    </Ü_D>

    <!-- Dolgozók -->

    <Dolgozo D_id="31">
        <Cim>
            <Utca>Oláh Lajos</Utca>
            <Varos>Miskolc</Varos>
            <Hazszam>6</Hazszam>
        </Cim>
        <Nev>Nagy Gergő</Nev>
        <Telefonszam>0670-5342490</Telefonszam>
        <Telefonszam>0630-6596521</Telefonszam>
    </Dolgozo>

    <Dolgozo D_id="32">
        <Cim>
            <Utca>Deaák ferenc</Utca>
            <Varos>Arnót</Varos>
            <Hazszam>8</Hazszam>
        </Cim>
        <Nev>Kiss Árpád</Nev>
        <Telefonszam>0670-5643905</Telefonszam>
        <Telefonszam>0630-6734524</Telefonszam>
    </Dolgozo>

    <Dolgozo D_id="33">
        <Cim>
            <Utca>Kossuth Lajos</Utca>
            <Varos>Miskolc</Varos>
            <Hazszam>56</Hazszam>
        </Cim>
        <Nev>Szabó Gergő</Nev>
        <Telefonszam>0670-5723490</Telefonszam>
        <Telefonszam>0630-9654321</Telefonszam>
    </Dolgozo>

</GQOKMW_BEADANDO>

=== DnyKristof/GQOKMW_XMLgyak/GQOKMW_BEADANDO/src/DomWriteOutPut_GQOKMW.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<GQOKMW_BEADANDO xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="XMLSchemaGQOKMW.xsd">
    <Vasarlo M_id="01" V_id="1">
        <Nev>Kiss Ádám</Nev>
        <Cim>
            <Utca>Kossuth Lajos utca</Utca>
            <Varos>Miskolc</Varos>
            <Hazszam>1</Hazszam>
        </Cim>
        <Telefonszam>0630-1234567</Telefonszam>
    </Vasarlo>
    <Vasarlo M_id="02" V_id="2">
        <Nev>Nagy Pista</Nev>
        <Cim>
            <Utca>Árpád utca</Utca>
            <Varos>Szekszárd</Varos>
            <Hazszam>5</Hazszam>
        </Cim>
        <Telefonszam>0630-3214569</Telefonszam>
    </Vasarlo>
    <Vasarlo M_id="03" V_id="3">
        <Nev>Nagy Máté</Nev>
        <Cim>
            <Utca>József Attila út</Utca>
            <Varos>Esztergom</Varos>
            <Hazszam>5</Hazszam>
        </Cim>
        <Telefonszam>0630-1234765</Telefonszam>
        <Telefonszam>0630-7654321</Telefonszam>
    </Vasarlo>
    <Megrendeles M_id="01">
        <Hatarido>2021-02-03</Hatarido>
        <Megrendelesideje>2021-02-01</Megrendelesideje>
        <Statusz>Teljesítve</Statusz>
    </Megrendeles>
    <Megrendeles M_id="02">
        <Hatarido>2021-02-07</Hatarido>
        <Megrendelesideje>2021-02-02</Megrendelesideje>
        <Statusz>Szállítás alatt</Statusz>
    </Megrendeles>
    <Megrendeles M_id="03">
        <Hatarido>2021-03-05</Hatarido>
        <Megrendelesideje>2021-03-01</Megrendelesideje>
        <Statusz>Teljesítve</Statusz>
    </Megrendeles>
    <Megrendelttermek MT_id="11" M_id="01">
        <Learazas>0.2</Learazas>
        <Mennyiseg>2</Mennyiseg>
        <Listaar>25000</Listaar>
    </Megrendelttermek>
    <Megrendelttermek MT_id="12" M_id="02">
        <Learazas>0.2</Learazas>
        <Mennyiseg>2</Mennyiseg>
        <Listaar>25000</Listaar>
    </Megrendelttermek>
    <Megrendelttermek MT_id="13" M_id="03">
        <Learazas>0.2</Learazas>
        <Mennyiseg>2</Mennyiseg>
        <Listaar>25000</Listaar>
    </Megrendelttermek>
    <Üzlet MT_id="11" Ü_id="21">
        <Cim>
            <Utca>Lajos utca</Utca>
            <Varos>Miskolc</Varos>
            <Hazszam>6</Hazszam>
        </Cim>
        <Nev>Hervis</Nev>
        <Telefonszam>0670-5312490</Telefonszam>
        <Telefonszam>0630-6587421</Telefonszam>
    </Üzlet>
    <Üzlet MT_id="12" Ü_id="22">
        <Cim>
            <Utca>Lajos utca</Utca>
            <Varos>Miskolc</Varos>
            <Hazszam>6</Hazszam>
        </Cim>
        <Nev>Intersport</Nev>
        <Telefonszam>0670-5312490</Telefonszam>
        <Telefonszam>0630-6587421</Telefonszam>
    </Üzlet>
    <Üzlet MT_id="13" Ü_id="23">
        <Cim>
            <Utca>Lajos utca</Utca>
            <Varos>Miskolc</Varos>
            <Hazszam>6</Hazszam>
        </Cim>
        <Nev>Dechatlon</Nev>
        <Telefonszam>0670-5312490</Telefonszam>
        <Telefonszam>0630-6587421</Telefonszam>
    </Üzlet>
    <Ü_D D_id="31" Ü_id="21">
        <Fizetes>420000</Fizetes>
    </Ü_D>
    <Ü_D D_id="32" Ü_id="22">
        <Fizetes>530000</Fizetes>
    </Ü_D>
    <Ü_D D_id="33" Ü_id="23">
        <Fizetes>370000</Fizetes>
    </Ü_D>
    <Dolgozo D_id="31">
        <Cim>
            <Utca>Oláh Lajos</Utca>
            <Varos>Miskolc</Varos>
            <Hazszam>6</Hazszam>
        </Cim>
        <Nev>Nagy Gergő</Nev>
        <Telefonszam>0670-5342490</Telefonszam>
        <Telefonszam>0630-6596521</Telefonszam>
    </Dolgozo>
    <Dolgozo D_id="32">
        <Cim>
            <Utca>Deaák ferenc</Utca>
            <Varos>Arnót</Varos>
            <Hazszam>8</Hazszam>
        </Cim>
        <Nev>Kiss Árpád</Nev>
        <Telefonszam>0670-5643905</Telefonszam>
        <Telefonszam>0630-6734524</Telefonszam>
    </Dolgozo>
    <Dolgozo D_id="33">
        <Cim>
            <Utca>Kossuth Lajos</Utca>
            <Varos>Miskolc</Varos>
            <Hazszam>56</Hazszam>
        </Cim>
        <Nev>Szabó Gergő</Nev>
        <Telefonszam>0670-5723490</Telefonszam>
        <Telefonszam>0630-9654321</Telefonszam>
    </Dolgozo>
</GQOKMW_BEADANDO>
